FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir pyyaml lightgbm scikit-learn pydantic pydantic-settings fastapi uvicorn mlflow prometheus-client pyarrow matplotlib plotly

COPY . /app

RUN pip install --no-cache-dir -e .

CMD ["python", "-m", "apps.trainer.run_stage", "--stage", "run_retrain_pipeline"]
